### PR TITLE
#29 - fix naming of files and links

### PR DESCRIPTION
**Pull request by fschuermeyer**
A Pull Request for Issue #29

### CODE REVIEW

**Comment by fschuermeyer** [comment]
@microsoft-github-policy-service agree

**Comment by fhinkel** [comment]
👋  Hi Felix, thanks for your PR! Changing the links like that doesn't work - those urls don't exist. Instead, we should swap rows 1.5 and 1.6 in the table. Do you want to take another stab at fixing the issue?

**Comment by fschuermeyer** [comment]
Thank you for your answer @fhinkel . I have adapted it according to your request.

**Comment by fhinkel** [comment]
Thanks so much! Now it matches the navigation on the left. Approved

**Review by fhinkel — APPROVED** [review]

**Pull request merged**
